### PR TITLE
Radu p13/test/task0

### PR DESCRIPTION
**Pull request by RaduP13**
made the nb and dt with all team members

### CODE REVIEW

**Review by Olivachet98 — APPROVED** [review]
great work sir

**Review by nickydime — APPROVED** [review]

**Comment by pierrotpetitpot** [comment]
approved

**Review by pierrotpetitpot — APPROVED** [review]
approved

**Comment by pierrotpetitpot** [comment]
approved

**Comment by pierrotpetitpot** [comment]
approbved

**Pull request merged**
